FinalBoss/Models/Hero.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace FinalBoss.Models
{
    [Table("heroes")]
    public class Hero
    {
        [Key]
        public int HeroId { get; set; }
        public string Name { get; set; }
        public string Weapon { get; set; }
        public byte[] Picture { get; set; }
        public virtual ICollection<Boss> Bosses { get; set; }

        // this only checks the id. previous c# projects also compare the other properties.
		public override bool Equals(System.Object otherHero)
		{
			if (!(otherHero is Hero))
			{
				return false;
			}
			else
			{
				Hero newHero = (Hero)otherHero;
				return this.HeroId.Equals(newHero.HeroId);
			}
		}

		public override int GetHashCode()
		{
			return this.HeroId.GetHashCode();
		}
    }
}

FinalBoss/Controllers/BossController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FinalBoss.Models;
using FinalBoss.ViewModels;
using System.IO;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace FinalBoss.Controllers
{
    public class BossController : Controller
    {
        private IBossRepository bossRepo;
        public BossController(IBossRepository repo = null)
        {
            if(repo == null)
            {
                this.bossRepo = new EFBossRepository();
            }
            else
            {
                this.bossRepo = repo;    
            }
        }

        public IActionResult Index(int? id = null, string name = null)
        {
            if (id != null && name != null)
            {
                ViewBag.ModalId = id;
                ViewBag.ModalName = name;

            }
            else
            {
                ViewBag.ModalId = null;
            }
            return View(bossRepo.Bosses.ToList());
        }


        // filter by immediate threat
        public IActionResult IndexThreat(bool threat)
        {
            
            return View(bossRepo.Bosses.Where(t => t.ImmediateThreat == threat).ToList());
        }

        public ViewResult Create()
        {
            var viewModel = new BossHeroes();
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(Boss boss, IFormFile image)
        {
            byte[] newImage = new byte[0];
            if(image != null) 
            {
                using (Stream fileStream = image.OpenReadStream())
                using (MemoryStream ms = new MemoryStream())
                { 
                    fileStream.CopyTo(ms);
                    newImage = ms.ToArray();
                }
                boss.Picture = newImage;
            }
            else
            {
                Console.WriteLine("No Image");    
            }

            bossRepo.Save(boss);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Boss thisBoss = bossRepo.Bosses.Include(boss => boss.Hero).FirstOrDefault(x => x.BossId == id);
            return View(thisBoss);
        }

        public IActionResult Edit(int id)
        {
            Boss thisBoss = bossRepo.Bosses.FirstOrDefault(x => x.BossId == id);
            var viewModel = new BossHeroes();
            viewModel.Boss = thisBoss;
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(Boss boss)
        {
            bossRepo.Edit(boss);

            return RedirectToAction("Index");
        }

		public ActionResult Delete(int id)
		{
			Boss thisBoss = bossRepo.Bosses.FirstOrDefault(x => x.BossId == id);
			return View(thisBoss);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteConfirmed(int id)
		{
            Boss thisBoss = bossRepo.Bosses.FirstOrDefault(x => x.BossId == id);
			bossRepo.Remove(thisBoss);   // Updated!
										 // Removed db.SaveChanges() call
			return RedirectToAction("Index");
		}

        // Toggles immediate threat level.
        [HttpPost]
        public IActionResult ToggleThreat(int id)
        {
            Boss thisBoss = bossRepo.Bosses.FirstOrDefault(x => x.BossId == id);
            thisBoss.ImmediateThreat = !thisBoss.ImmediateThreat;
            bossRepo.Edit(thisBoss);
            return RedirectToAction("Index"); 
        }

        public IActionResult GetPicture(int id)
        {
            var thisPicture = bossRepo.Bosses.FirstOrDefault(x => x.BossId == id).Picture;
            return File(thisPicture, "image/png");
        }
    }
}

FinalBoss/Controllers/HeroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FinalBoss.Models;
using System.IO;
using Microsoft.EntityFrameworkCore;

namespace FinalBoss.Controllers
{
    public class HeroController : Controller
    {
        private IHeroRepository heroRepo;
        public HeroController(IHeroRepository repo = null)
        {
            if(repo == null)
            {
                this.heroRepo = new EFHeroRepository();
            }
            else
            {
                this.heroRepo = repo;
            }
        }

        public IActionResult Index(int? id = null, string name = null)
        {
			if (id != null && name != null)
			{
				ViewBag.ModalId = id;
				ViewBag.ModalName = name;

			}
			else
			{
				ViewBag.ModalId = null;
			}
            return View(heroRepo.Heroes.ToList());
        }

        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Hero hero, IFormFile image)
        {
            byte[] newImage = new byte[0];
            if(image != null)
            {
                using (Stream fileStream = image.OpenReadStream())
                using (MemoryStream ms = new MemoryStream())
                {
                    fileStream.CopyTo(ms);
                    newImage = ms.ToArray();
                }
                hero.Picture = newImage;
            }
            else
            {
                Console.WriteLine("No Image");
            }

            heroRepo.Save(hero);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Hero thisHero = heroRepo.Heroes.FirstOrDefault(x => x.HeroId == id);
            return View(thisHero);
        }

        [HttpPost]
        public IActionResult Edit(Hero hero)
        {
            heroRepo.Edit(hero);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Hero thisHero = heroRepo.Heroes.Include(hero => hero.Bosses).FirstOrDefault(x => x.HeroId == id);
            return View(thisHero);
        }

        public ActionResult Delete(int id)
        {
            Hero thisHero = heroRepo.Heroes.FirstOrDefault(x => x.HeroId == id);
            return View(thisHero);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            Hero thisHero = heroRepo.Heroes.FirstOrDefault(x => x.HeroId == id);
            heroRepo.Remove(thisHero);
            return RedirectToAction("Index");
        }

		public IActionResult GetPicture(int id)
		{
			var thisPicture = heroRepo.Heroes.FirstOrDefault(x => x.HeroId == id).Picture;
			return File(thisPicture, "image/png");
		}
    }
}

FinalBoss/Views/Hero/Create.cshtml
@model FinalBoss.Models.Hero

@{    ViewData["Title"] = "Hero List";
    Layout = "_Layout";
}

<h2>Add dis hero</h2>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype="multipart/form-data"}))
{
    <p>
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
   </p>
    <p>
        @Html.LabelFor(model => model.Weapon)
        @Html.TextBoxFor(model => model.Weapon)
    </p>

    <p>
        Upload Image
        <input type="file" id="Image" name="Image" />
    </p>

    <input type="submit" value="Enter Boss"/>
}
<p>
    @Html.ActionLink("Return to boss list", "Index")
</p>

FinalBoss/Views/Hero/Details.cshtml
@model FinalBoss.Models.Hero

@{    ViewData["Title"] = "Hero Details";
    Layout = "_Layout";
}

<h1>@Model.Name</h1>
@if(Model.Picture != null)
{
    <p>
        <img src='@Url.Action("GetPicture", "Hero", new { id = Model.HeroId})'/>
    </p>
}
else
{
    <p>
       no pics. imagination works best.
    </p>
}
    <p>
        Weapon: @Model.Weapon
    </p>

    @foreach(var boss in Model.Bosses)
    {
        <p><img class="thumbnail" src='@Url.Action("GetPicture", "Boss", new { id = @boss.BossId })'/>@boss.Name</p>
    }
    <p>@Html.ActionLink("Return to boss list", "Index")</p>

FinalBoss/Views/Hero/Edit.cshtml
@model FinalBoss.Models.Hero

@{    
    ViewData["Title"] = "Hero Edit";
    Layout = "_Layout";
}

<h1>Edit</h1>

@using (Html.BeginForm())
{
    <p>
        @Html.HiddenFor(model => model.HeroId)
    </p>

    <p>
        @Html.LabelFor(model => model.Name)
        @Html.EditorFor(model => model.Name)
    </p>

    <p>
        @Html.LabelFor(model => model.Weapon)
        @Html.EditorFor(model => model.Weapon)
    </p>

    <p>
        @Html.HiddenFor(model => model.Picture)
    </p>

    <input type="submit" value="Save Changes"/>
}
@Html.ActionLink("Back to Heroes List", "Index")

FinalBoss/Views/Hero/Index.cshtml
@using FinalBoss.Models

@{
    ViewData["Title"] = "Hero List";
    Layout = "_Layout";
}

ima boss splash
<p>
    @Html.ActionLink("Add Hero", "Create")
</p>

@foreach(var hero in Model)
{
    <p>
        <strong>@hero.Name</strong> | 
        @Html.ActionLink("Details", "Details", new { id = @hero.HeroId }) | 
        @Html.ActionLink("Edit", "Edit", new { id = @hero.HeroId }) |
        @Html.ActionLink("Delete", "Index", new { id = @hero.HeroId, name = @hero.Name }) 
    </p>

}
<p>
    @Html.ActionLink("Return to boss splash", "Index", "Home")
</p>

@if (ViewBag.ModalId != null)
{
    <div class="modal">
        <h1>Has @ViewBag.ModalName truly fallen?</h1>
        @using (Html.BeginForm("Delete", "Hero", new { id = ViewBag.ModalId}))
        {
            <input type="submit" value="*Sob Uncontrollably*"/>
        }
	    @Html.ActionLink("They Live!!", "Index", new { @class = "exit-x"})

    </div>
}